import { defineRegistryGroup } from "@rlz/registry";

export const registryBaseComponents = defineRegistryGroup("component", {
  backdrop: {
    name: "Backdrop",
    description: "A component that provides a backdrop effect.",
    path: "components/base/backdrop.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  "menu-base": {
    name: "Menu Base",
    description: "A component that provides a menu base.",
    path: "components/base/menu-base.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  "popup-arrow": {
    name: "Popup Arrow",
    description: "A component that provides a popup arrow.",
    path: "components/base/popup-arrow.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  shortcut: {
    name: "Shortcut",
    description: "A component that provides a shortcut.",
    path: "components/base/shortcut.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  "x-close": {
    name: "X Close",
    description: "A component that provides a close button.",
    path: "components/base/x-close.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
});
