import { defineRegistry } from "@rlz/registry";

export const registryBaseComponents = defineRegistry({
  backdrop: {
    name: "backdrop",
    type: "component",
    description: "A component that provides a backdrop effect.",
    path: "components/base/backdrop.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  "menu-base": {
    name: "menu-base",
    type: "component",
    description: "A component that provides a menu base.",
    path: "components/base/menu-base.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  "popup-arrow": {
    name: "popup-arrow",
    type: "component",
    description: "A component that provides a popup arrow.",
    path: "components/base/popup-arrow.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  shortcut: {
    name: "shortcut",
    type: "component",
    description: "A component that provides a shortcut.",
    path: "components/base/shortcut.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
  "x-close": {
    name: "x-close",
    type: "component",
    description: "A component that provides a close button.",
    path: "components/base/x-close.tsx",
    destPath: "base",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
    allowManualInstall: false,
  },
});
