import { defineRegistryGroup } from "@rlz/registry";

export const registryComponents = defineRegistryGroup("component", {
  accordion: {
    name: "accordion",
    description: "A collapsible panel that can be expanded or collapsed",
    path: "components/ui/accordion.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  "alert-dialog": {
    name: "alert-dialog",
    description: "A modal dialog for important alerts and confirmations",
    path: "components/ui/alert-dialog.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "backdrop"],
  },
  alert: {
    name: "alert",
    description: "An inline alert message component",
    path: "components/ui/alert.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  autocomplete: {
    name: "autocomplete",
    description: "An input with suggestion and autocompletion capabilities",
    path: "components/ui/autocomplete.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "input", "scroll-area", "popup-arrow"],
  },
  avatar: {
    name: "avatar",
    description: "A user avatar image or fallback initials component",
    path: "components/ui/avatar.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  badge: {
    name: "badge",
    description: "A small badge used to display counts or statuses",
    path: "components/ui/badge.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  breadcrumb: {
    name: "breadcrumb",
    description: "A breadcrumb navigation component",
    path: "components/ui/breadcrumb.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  button: {
    name: "button",
    description: "A styled button component",
    path: "components/ui/button.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  card: {
    name: "card",
    description: "A container card for grouping related content",
    path: "components/ui/card.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  checkbox: {
    name: "checkbox",
    description: "A checkbox input component",
    path: "components/ui/checkbox.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  collapsible: {
    name: "collapsible",
    description: "A generic collapsible container component",
    path: "components/ui/collapsible.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  combobox: {
    name: "combobox",
    description: "A combobox input with dropdown selection",
    path: "components/ui/combobox.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: [
      "cn",
      "scroll-area",
      "input",
      "popup-arrow",
      "button",
    ],
  },
  command: {
    name: "command",
    description: "A command palette or searchable action list",
    path: "components/ui/command.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "autocomplete", "backdrop", "shortcut"],
  },
  "context-menu": {
    name: "context-menu",
    description: "A right-click context menu component",
    path: "components/ui/context-menu.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "menu-base", "shortcut"],
  },
  dialog: {
    name: "dialog",
    description: "A generic modal dialog component",
    path: "components/ui/dialog.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "backdrop", "scroll-area", "x-close"],
  },
  drawer: {
    name: "drawer",
    description: "A slide-over drawer component",
    path: "components/ui/drawer.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "backdrop", "scroll-area", "x-close"],
  },
  empty: {
    name: "empty",
    description: "A placeholder component for empty states",
    path: "components/ui/empty.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  field: {
    name: "field",
    description: "A form field wrapper component",
    path: "components/ui/field.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  fieldset: {
    name: "fieldset",
    description: "A fieldset grouping component for forms",
    path: "components/ui/fieldset.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  form: {
    name: "form",
    description: "Form utilities and wrapper component",
    path: "components/ui/form.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  group: {
    name: "group",
    description: "A simple grouping/layout component",
    path: "components/ui/group.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn", "separator"],
  },
  "input-group": {
    name: "input-group",
    description: "A wrapper for grouping input-related elements",
    path: "components/ui/input-group.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn", "input", "textarea"],
  },
  input: {
    name: "input",
    description: "A text input component",
    path: "components/ui/input.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  kbd: {
    name: "kbd",
    description: "A keyboard key visual component",
    path: "components/ui/kbd.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  label: {
    name: "label",
    description: "A label component for form inputs",
    path: "components/ui/label.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  menu: {
    name: "menu",
    description: "A dropdown or contextual menu component",
    path: "components/ui/menu.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "popup-arrow", "menu-base", "shortcut"],
  },
  menubar: {
    name: "menubar",
    description: "A menubar/navigation menu component",
    path: "components/ui/menubar.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  meter: {
    name: "meter",
    description: "A visual meter/progress indicator",
    path: "components/ui/meter.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  "number-field": {
    name: "number-field",
    description: "A numeric input field component",
    path: "components/ui/number-field.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "label"],
  },
  "otp-field": {
    name: "otp-field",
    description: "A otp input field component",
    path: "components/ui/otp-field",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "separator"],
  },
  popover: {
    name: "popover",
    description: "A contextual popover component",
    path: "components/ui/popover.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "popup-arrow"],
  },
  "preview-card": {
    name: "preview-card",
    description: "A card component for previewing content",
    path: "components/ui/preview-card.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "popup-arrow"],
  },
  progress: {
    name: "progress",
    description: "A progress bar component",
    path: "components/ui/progress.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  "radio-group": {
    name: "radio-group",
    description: "A group of radio inputs",
    path: "components/ui/radio-group.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  "scroll-area": {
    name: "scroll-area",
    description: "A scrollable container with custom scrollbars",
    path: "components/ui/scroll-area.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  select: {
    name: "select",
    description: "A select dropdown component",
    path: "components/ui/select.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "button"],
  },
  separator: {
    name: "separator",
    description: "A visual separator/divider component",
    path: "components/ui/separator.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  skeleton: {
    name: "skeleton",
    description: "A skeleton loader placeholder component",
    path: "components/ui/skeleton.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  slider: {
    name: "slider",
    description: "A range slider input component",
    path: "components/ui/slider.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  switch: {
    name: "switch",
    description: "A toggle switch input component",
    path: "components/ui/switch.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  table: {
    name: "table",
    description: "A table component for tabular data",
    path: "components/ui/table.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  tabs: {
    name: "tabs",
    description: "A tabs navigation component",
    path: "components/ui/tabs.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  textarea: {
    name: "textarea",
    description: "A multi-line text input component",
    path: "components/ui/textarea.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  toast: {
    name: "toast",
    description: "A transient notification/toast component",
    path: "components/ui/toast.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn", "button"],
  },
  toggle: {
    name: "toggle",
    description: "A toggle button component",
    path: "components/ui/toggle.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn"],
  },
  toolbar: {
    name: "toolbar",
    description: "A toolbar container for action buttons and controls",
    path: "components/ui/toolbar.tsx",
    version: "1.0.0",
    dependencies: [],
    registryDependencies: ["cn"],
  },
  tooltip: {
    name: "tooltip",
    description: "A tooltip component for contextual hints",
    path: "components/ui/tooltip.tsx",
    version: "1.0.0",
    dependencies: ["class-variance-authority"],
    registryDependencies: ["cn", "popup-arrow"],
  },
});
