export const demoPaths: Record<string, string> = {
  // Accordion
  accordion: "accordion/default",
  "accordion-multiple": "accordion/multiple",
  "accordion-disabled": "accordion/disabled",
  "accordion-icon": "accordion/icon",
  // Alert
  alert: "alert/default",
  "alert-with-icon": "alert/with-icon",
  "alert-warning": "alert/warning",
  "alert-error": "alert/error",
  "alert-success": "alert/success",
  "alert-info": "alert/info",
  "alert-action": "alert/action",
  // Alert Dialog
  "alert-dialog": "alert-dialog/default",
  "alert-dialog-bare": "alert-dialog/bare",
  // Autocomplete
  autocomplete: "autocomplete/default",
  "autocomplete-disabled": "autocomplete/disabled",
  "autocomplete-inline": "autocomplete/inline",
  "autocomplete-auto-highlight": "autocomplete/auto-highlight",
  "autocomplete-group": "autocomplete/group",
  "autocomplete-clear": "autocomplete/clear",
  // Avatar
  avatar: "avatar/default",
  "avatar-size": "avatar/size",
  "avatar-stack": "avatar/stack",
  // Badge
  badge: "badge/default",
  "badge-variant": "badge/variant",
  // Breadcrumb
  breadcrumb: "breadcrumb/default",
  "breadcrumb-custom-separator": "breadcrumb/custom-separator",
  // Button
  button: "button/default",
  "button-size": "button/size",
  "button-disabled": "button/disabled",
  "button-variants": "button/variant",
  "button-spinner": "button/spinner",
  "button-button-group": "button/button-group",
};
