export const demoPaths: Record<string, string> = {
  // Accordion
  accordion: "accordion/default",
  "accordion-multiple": "accordion/multiple",
  "accordion-disabled": "accordion/disabled",
  "accordion-icon": "accordion/icon",
  // Alert
  alert: "alert/default",
  "alert-with-icon": "alert/with-icon",
  "alert-warning": "alert/warning",
  "alert-error": "alert/error",
  "alert-success": "alert/success",
  "alert-info": "alert/info",
  "alert-action": "alert/action",
  // Alert Dialog
  "alert-dialog": "alert-dialog/default",
  "alert-dialog-bare": "alert-dialog/bare",
  // Autocomplete
  autocomplete: "autocomplete/default",
  "autocomplete-disabled": "autocomplete/disabled",
  "autocomplete-inline": "autocomplete/inline",
  "autocomplete-auto-highlight": "autocomplete/auto-highlight",
  "autocomplete-group": "autocomplete/group",
  "autocomplete-clear": "autocomplete/clear",
  "autocomplete-input-group": "autocomplete/input-group",
  // Avatar
  avatar: "avatar/default",
  "avatar-size": "avatar/size",
  "avatar-stack": "avatar/stack",
  // Badge
  badge: "badge/default",
  "badge-variant": "badge/variant",
  // Breadcrumb
  breadcrumb: "breadcrumb/default",
  "breadcrumb-custom-separator": "breadcrumb/custom-separator",
  // Button
  button: "button/default",
  "button-size": "button/size",
  "button-disabled": "button/disabled",
  "button-variants": "button/variant",
  "button-spinner": "button/spinner",
  "button-group": "button/button-group",
  // Card
  card: "card/default",
  // Checkbox
  checkbox: "checkbox/default",
  "checkbox-disabled": "checkbox/disabled",
  "checkbox-card": "checkbox/card",
  "checkbox-group": "checkbox/group",
  "checkbox-parent": "checkbox/parent",
  "checkbox-nested": "checkbox/nested-parent",
  // Collapsible
  collapsible: "collapsible/default",
  // Combobox
  combobox: "combobox/default",
  "combobox-disabled": "combobox/disabled",
  "combobox-autohighlight": "combobox/autohighlight",
  "combobox-clear": "combobox/clear",
  "combobox-group": "combobox/group",
  "combobox-trigger": "combobox/trigger",
  "combobox-multiple": "combobox/multiple",
  "combobox-indicator": "combobox/indicator",
  "combobox-input-group": "combobox/input-group",
  //Command
  command: "command/default",
  // Context Menu
  "context-menu": "context-menu/default",
  // Dialog
  dialog: "dialog/default",
  "dialog-variant": "dialog/variant",
  "dialog-terms": "dialog/terms",
  "dialog-nested": "dialog/nested",
  // Drawer
  drawer: "drawer/default",
  "drawer-variant": "drawer/variant",
  "drawer-inset": "drawer/inset",
  "drawer-nested": "drawer/nested",
  "drawer-nested-inset": "drawer/nested-inset",
  "drawer-indent": "drawer/indent",
  "drawer-swipe-area": "drawer/swipe-area",
  "drawer-action": "drawer/action",
  "drawer-swipe-direction": "drawer/swipe-direction",
  // Empty
  empty: "empty/default",
  "empty-media": "empty/media",
  // Field
  field: "field/default",
  // Fieldset
  fieldset: "fieldset/default",
  // Form
  form: "form/default",
  // Group
  group: "group/default",
  "group-orientation": "group/orientation",
  "group-size": "group/size",
  "group-input-group": "group/input-group",
  "group-text": "group/text",
  // Input
  input: "input/default",
  "input-disabled": "input/disabled",
  "input-variant": "input/variant",
  "input-file": "input/file",
  // Input Group
  "input-group": "input-group/default",
  "input-group-text": "input-group/text",
  "input-group-textarea": "input-group/textarea",
  "input-group-button": "input-group/button",
  "input-group-kbd": "input-group/kbd",
  "input-group-label": "input-group/label",
  // Kbd
  kbd: "kbd/default",
  "kbd-input-group": "kbd/input-group",
  // label
  label: "label/default",
  // Radio group
  "radio-group": "radio-group/default",
  "radio-group-disabled": "radio-group/disabled",
  // Switch
  switch: "switch/default",
  "switch-disabled": "switch/disabled",
};
